name: rtd38
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy~=0.18.0
  - python=3.7
  - pip>=20.1  # pip is needed as dependency
  - pytest~=7.1.1
  - climind~=0.1
  - xarray~=0.20.2
  - geopandas~=0.9.0
  - numpy~=1.21.5
  - pandas~=1.3.4
  - shapely~=1.7.1
  - jsonschema~=4.7.1
  - matplotlib~=3.3.1
  - jinja2~=3.0.3
  - cdsapi~=0.5.1
  - requests~=2.24.0
  - python-dotenv~=0.20.0
  - beautifulsoup4~=4.10.0
  - seaborn~=0.11.2
  - regionmask~=0.9.0
  - python-dateutil~=2.8.1
  - cftime~=1.5.1.1
  - setuptools~=50.3.0
  - pip:
    - black==20.8b1
